---
driver:
#  name: docker
  driver_plugin: docker_ssh
provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: centos-7.0

suites:
  - name: mysql
    run_list:
      - recipe[exampleloginapp::mysql]
    attributes:

  - name: swarm_master
    run_list:
      - recipe[exampleloginapp::swarm_master]
    attributes:
