name 'exampleloginapp'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures exampleloginapp'
long_description 'Installs/Configures exampleloginapp'
version '0.1.21'

depends 'docker', '~> 2.0'
depends 'mysql', '~> 6.0'
